"""add secret field to device

Revision ID: 1fb965afadf4
Revises: 202506041309
Create Date: 2025-04-06 16:25:55.675865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fb965afadf4'
down_revision = '202506041309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secret', sa.String(length=256), nullable=True))
        batch_op.alter_column('hashed_device_key',
               existing_type=sa.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=False,
               existing_server_default=sa.text("('')"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.alter_column('hashed_device_key',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.drop_column('secret')

    # ### end Alembic commands ###
