"""Add hashed_device_key column to device table

Revision ID: 202506041309
Revises: 6c75f9f4f71e
Create Date: 2025-06-04 13:09:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202506041309'
down_revision = '6c75f9f4f71e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hashed_device_key', sa.String(length=256), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_column('hashed_device_key')

    # ### end Alembic commands ###
